require 'http'

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzI4NTg3ODB9.TulmQsigmCCJkOXBa5GFmg9MPgyNcLyp70h-0STNP1E
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "amanda@example.com",
  "password": "password",
  "password_confirmation": "password"
} 

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "amanda@example.com",
  "password": "password"
}

### Sleep create
POST http://localhost:3000/sleeps.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "asleep": "22:00",
  "awake": "7:00",
  "date": "2023-01-02"
}

### Sleep index

GET http://localhost:3000/sleeps.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Sleep show
GET http://localhost:3000/sleeps/6.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Sleep destroy
DELETE http://localhost:3000/sleeps/7.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Sleep update
PATCH http://localhost:3000/sleeps/8.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ "asleep": "22:00",
  "awake": "7:00",
  "date": "2023-02-01" }

### water index
  GET http://localhost:3000/waters.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### water show
  GET http://localhost:3000/waters/9.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### water create
POST http://localhost:3000/waters.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "time": "7:00",
  "date": "2023-01-03",
  "amount": "1"
}

### water update
PATCH http://localhost:3000/waters/9.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "time": "23:00",
  "date": "2023-01-03",
  "amount": "3"
}

### water destroy
DELETE http://localhost:3000/waters/9.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### goal create
POST http://localhost:3000/goals.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "goal": "7 cups",
  "category": "water"
}

### goal update
PATCH http://localhost:3000/goals/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "goal": "5 cups",
  "category": "water"
}

### goal delete
DELETE http://localhost:3000/goals/6.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### goal index
GET http://localhost:3000/goals.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### goal show
GET http://localhost:3000/goals/6.json
Content-Type: application/json
Authorization: Bearer {{jwt}}